title: "selfdriven YTou"
description: ""
baseurl: ""
url: ""
context: "you"
repo: "selfdriven-foundation/selfdriven-you"

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: selfdriven

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - _well-known/